@startuml
'https://plantuml.com/activity-diagram-beta

|Kunde|
start
:gå til brugerdefineret hjemmeside;
|Shop|
:vælg egenskaber på carport<
|Kunde|
:Send Forespørgsel;
|Mail|
:Forespørgsel]
:Send Mail with Forespørgsel;
|Sælger|
:Mail]
:modtage Mail;
:indtast data i tilbuds program;
|Tilbuds Program|
:beregn tegninger, lister og pris;
|Sælger|
if(brugbare mål?) is (nej) then
:ring til kunde;
|Kunde|
:godkend nye mål;
else (ja)
end if
|Sælger|
if(brugbare mål?) is (nej) then
:find ny løsning;
:ring til kunde;
|Kunde|
:godkend løsning;
else (ja)
end if
|Sælger|
:vælg pris med tilbud;
:send tilbud til kunde;
|Mail|
:Tilbud]
|Kunde|
if(kunden er glad) is (yes) then
:godkendelse på tilbud;
|Shop|
:Betaling]
|Mail|
:Mail]
|Sælger|
if(stadig har tilbud åbent) is (no) then
:tag mail og indtast i tilbudsprogramet igen;
|Tilbuds Program|
:beregn tegninger, lister og pris;
else (yes)
end if
|Sælger|
:plokliste]
:send plokliste til kunde via email;
|Mail|
:plokliste]
|Kunde|
:modtag plokliste;
:plokliste]
else (no)
end if
stop

@enduml
