@startuml
Title DomainModel
hide circle
hide methods

class Customer {
    email
}
class Admin{
    userName
}
class Orders{
    carport
}
class Carport{
    size
}
class Shed{
    size
}
class CarportCustomizer{
    calculator
}

Orders "*" -up- "1" Customer: generates <
Admin "1" -left- "*" Orders: > custemizes
Orders "1" -down- "1" Carport: has >
Carport "1" -right- "0-1" Shed: has >
Admin "1" -up- "1" CarportCustomizer :uses >


@enduml