@startuml
package "Prebuilt" #FFB52E {
    Object carport {
        Serial uID
        int length_cm
        int width_cm
        int shed_length
        int shed_width
        int slope_degrees
        Serial oID
        Double price
    }
}

package "Materials" #ffb {
    Object material_variant {
        Serial uID
        Serial mID
        String description
    }
    Object material {
        Serial mID
        String name
        MTYPE type
        int length_mm
        int width_mm
        int depth_mm
        Double price
    }

    'nice to have - if a material has this it's a roof that requires a slope
    Object requires_slope {
        Serial mID
        tinyint min_slope
        tinyint max_slope
    }
}

package "Orders" #00CDFF {
    Object orders {
        Serial oID
        int length_cm
        int width_cm
        int shed_length_cm
        int shed_width_cm
        int slope_degrees
        boolean hire_assembler
        Double price
        STATUS status
    }
    Object order_item {
        Serial ID
        Serial oID
        Serial mID
        tinyint quantity
    }
}

package Enum #aad {
    Object STATUS {
        initialised
        processing
        waiting_for_customer
        accepted
        paid
    }
    Object MTYPE {
        roof
        pillar
        beam
        cover_planks
    }
}

orders <|.. STATUS
material <|.. MTYPE
order_item --> material_variant
carport -> order_item
order_item <- orders
material_variant --> material
requires_slope -> material_variant

@enduml