@startuml
package "Prebuilt" #FFB52E {
    Object carport {
        Serial carportID
        int length_cm
        int width_cm
        int shed_length_cm
        int shed_width_cm
        int slope_degrees
        Serial order_itemID
        Double price
    }
}

package "Materials" #ffb {
    Object material_variant {
        Serial mvID
        Serial materialID
        int length_cm
        Double price
    }
    Object material {
        Serial materialID
        String name
        MTYPE type
        int width_mm
        int depth_mm
        String description
    }

    'nice to have - if a material has this it's a roof that requires a slope
    Object requires_slope {
        Serial materialID
        smallint min_slope
        smallint max_slope
    }
}

package "Orders" #00CDFF {
    Object order_item {
        Serial order_itemID
        Serial orderID
        Serial mvID
        tinyint quantity
    }
    Object orders {
        Serial orderID
        int length_cm
        int width_cm
        int shed_length_cm
        int shed_width_cm
        int slope_degrees
        boolean hire_assembler
        Double price
        STATUS status
    }
}

package Enum #aad {
    Object STATUS {
        initialised
        processing
        waiting_for_customer
        accepted
        paid
    }
    Object MTYPE {
        roof
        pillar
        beam
        cover_planks
    }
}

orders <|.. STATUS
material <|.. MTYPE
order_item --> material_variant
carport -> order_item
order_item <- orders
material_variant --> material
requires_slope -> material_variant

@enduml