@startuml
'https://plantuml.com/activity-diagram-beta

|Kunde|
package "Userstory 6 & 17" #FFB{
start
:Gå til hjemmeside;
|Shop|
:Tilpas forespørgsel til carport<
|Kunde|
:Send forespørgsel;
|Shop|
:Modtag Forespørgsel;
:Generér hyperlink;
|E-mail|
:Hyperlink med data fra forespørgsel]
}
package "Userstory 8 & 13" #FBA{
|Sælger|
:Modtag hyperlink;
:Klik hyperlink til hjemmesiden med forespørgselsdata;
|Sælger|
:Vurdér mål;
if(Realistiske mål?) is (Nej) then
:Kom med ny mulig løsning;
else (Ja)
end if
:Kontakt kunde;
|Kunde|
:Modtag ny mulig løsning;
if (Acceptabel løsning?) is (Nej) then
|Sælger|
:Find på løsning sammen;
else (Ja)
end if
:Ny løsning]
|Sælger|
:Modtag løsning;
:Vurdér løsning;
}
|Shop|
:Beregn mål, rendér plantegning og stykliste;
:Beregn pris;
|Sælger|
:Send tilbud til kunde;
|E-mail|
:Tilbud]
|Kunde|
:Godkend tilbud;
:Betal?;
stop

@enduml
